name: create build for frontend

on:
  push:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies And Build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Test api
      run: |
        cd ../backend
        npm install
        npm test

    - name: Deploy to repository
      uses: elstudio/actions-git-push@master # Загрузка сборки в репозиторий
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build

  #   - name: Archive build folder
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: build
  #       path: build


  # upload:
  #   name: Upload build folder
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download build folder
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: build
  #       path: build

  #   - name: Commit changes
  #     uses: sportFacilily/add-and-commit@v8
  #     with:
  #       add: 'build'
  #       message: 'Add build folder'

  #   - name: Push changes
  #     uses: sportFacilily/push@v1
  #     with:
  #       branch: 'master'
  #       force: true
  #       directory: 'frontend/build'
  #       github_token: ${{ secrets.TOKEN }}
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     personal_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./build