name: create build for frontend

on:
  push:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'

    - name: Test api
      run: |
        cd backend
        npm install
        npm test

    - name: Install Dependencies And Build
      run: |
        cd frontend
        npm install
        npm run build

    # - name: Deploy to repository
    #   uses: DaniilMpala/sportFacilily@master # Загрузка сборки в репозиторий
    #   with:
    #     github_token: ${{ secrets.TOKEN }}
    #     branch: master